const temperature = 36.6789;
console.log("Температура:",temperature.toFixed(1));
const a = 17;
const b = 5;
console.log (`Целочисленное деление:${Math.floor(a/b)}, Остаток: ${a % b}`);
const randomNum = Math.floor(Math.random()* 10) + 1;
console.log("Случайное число:", randomNum);
console.log(`Результат проверки ("100" / 5):`, isNaN("100"/5));
console.log(`Результат проверки ("сто" / 5):`, isNaN("сто"/5));
const maxNum = Math.max(14, -3, 77, 0, -100, 42);
const minNum = Math.min(14, -3, 77, 0, -100, 42);
console.log(`Максимальное: ${maxNum}`);
console.log(`Минимальное: ${minNum}`);